service: hello-js-project
frameworkVersion: "2"

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:eu-west-1:187917125870:layer:HelloJsLayer:1
